### ISSUE TITLE
Run rustfmt and clippy on the CI

### ISSUE THREAD

**Issue by sorairolake** [dyz1990/sevenz-rust#38]
I suggest to add something like the following to `rust.yml`:

```yaml
    - name: Check rustfmt
      run: cargo fmt -- --check
    - name: Check clippy
      run: cargo clippy -- -D warnings
    - run: cargo clippy --all-features -- -D warnings
    - run: cargo clippy --no-default-features -- -D warnings
```

I think this helps maintain the code quality.
